import React, { useMemo } from 'react';
import * as THREE from 'three';
import { ThreeCanvas } from '@remotion/three';
import { useThree } from '@react-three/fiber';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { useCurrentFrame } from 'remotion';

/**
 * MolecularNetwork — a dense, beautifully rendered 3D macromolecule.
 * Generates an Icosahedron-based spherical lattice of atoms and bonds,
 * with physically based glossy materials (PBR) and a solid black background
 * matching the user's reference image.
 */

interface MolecularNetworkProps {
  width?: number;
  height?: number;
  totalFrames?: number;
  speed?: number;
}

// Deterministic pseudo-random function for consistent generation
const pseudoRandom = (seed: number) => {
  const x = Math.sin(seed * 999.99) * 10000;
  return x - Math.floor(x);
};

const Environment: React.FC = () => {
  const { gl, scene } = useThree();
  useMemo(() => {
    const pmrem = new THREE.PMREMGenerator(gl);
    scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
    pmrem.dispose();
  }, [gl, scene]);
  return null;
};

const Molecule: React.FC<{ u: number }> = ({ u }) => {
  const { mainAtoms, sideAtoms, edges } = useMemo(() => {
    // Generate a spherical lattice using a subdivided Icosahedron
    const geo = new THREE.IcosahedronGeometry(7, 2);
    
    // 1. Extract unique vertices for main atoms
    const vMap = new Map<string, THREE.Vector3>();
    const pos = geo.attributes.position;
    for (let i = 0; i < pos.count; i++) {
      const v = new THREE.Vector3(pos.getX(i), pos.getY(i), pos.getZ(i));
      // Truncate precision to merge overlapping vertices generated by the geometry
      const key = `${v.x.toFixed(2)}_${v.y.toFixed(2)}_${v.z.toFixed(2)}`;
      if (!vMap.has(key)) vMap.set(key, v);
    }
    const uniqueVertices = Array.from(vMap.values());

    // Vibrant color palette from the reference image
    const palette = [
      '#e62020', // Bright Red
      '#053060', // Dark Blue
      '#0080c0', // Med Blue
      '#20c0e0', // Light Blue/Cyan
      '#10a080', // Green
      '#f09040', // Orange
      '#f0a0a0', // Pink
    ];
    
    const mainAtoms = uniqueVertices.map((v, i) => {
      const color = palette[Math.floor(pseudoRandom(i) * palette.length)];
      return { pos: v, color };
    });

    // 2. Extract edges for bonds using WireframeGeometry
    const wire = new THREE.WireframeGeometry(geo);
    const wPos = wire.attributes.position;
    const edges: { p1: THREE.Vector3; p2: THREE.Vector3 }[] = [];
    
    // Deduplicate edges so we only draw one cylinder per bond
    const edgeMap = new Set<string>();
    
    for (let i = 0; i < wPos.count; i += 2) {
      const p1 = new THREE.Vector3(wPos.getX(i), wPos.getY(i), wPos.getZ(i));
      const p2 = new THREE.Vector3(wPos.getX(i + 1), wPos.getY(i + 1), wPos.getZ(i + 1));
      
      const k1 = `${p1.x.toFixed(2)}_${p1.y.toFixed(2)}_${p1.z.toFixed(2)}`;
      const k2 = `${p2.x.toFixed(2)}_${p2.y.toFixed(2)}_${p2.z.toFixed(2)}`;
      const edgeKey = k1 < k2 ? `${k1}-${k2}` : `${k2}-${k1}`;
      
      if (!edgeMap.has(edgeKey)) {
        edgeMap.add(edgeKey);
        edges.push({ p1, p2 });
      }
    }

    // 3. Generate side atoms (like small Hydrogen atoms sticking out)
    const sideAtoms: { pos: THREE.Vector3; color: string }[] = [];
    mainAtoms.forEach((atom, i) => {
      const normal = atom.pos.clone().normalize();
      
      // Add 1 or 2 outer atoms to fill the silhouette
      const numSide = pseudoRandom(i + 1000) > 0.4 ? 2 : 1;
      for (let k = 0; k < numSide; k++) {
        const jitter = new THREE.Vector3(
          (pseudoRandom(i + k * 10) - 0.5) * 1.2,
          (pseudoRandom(i + k * 20) - 0.5) * 1.2,
          (pseudoRandom(i + k * 30) - 0.5) * 1.2
        );
        const dir = normal.clone().add(jitter).normalize();
        const sidePos = atom.pos.clone().add(dir.multiplyScalar(1.6));
        
        // Slight cream/white variations for side atoms
        const sideColor = pseudoRandom(i + k) > 0.5 ? '#ffffff' : '#ffe8e0';
        sideAtoms.push({ pos: sidePos, color: sideColor });
        edges.push({ p1: atom.pos, p2: sidePos });
      }
    });

    return { mainAtoms, sideAtoms, edges };
  }, []);

  // Shared geometry and materials for performance
  const sphereGeoMain = useMemo(() => new THREE.SphereGeometry(0.65, 32, 32), []);
  const sphereGeoSide = useMemo(() => new THREE.SphereGeometry(0.35, 24, 24), []);
  const cylinderGeo = useMemo(() => new THREE.CylinderGeometry(0.15, 0.15, 1, 12), []);
  
  const bondMat = useMemo(() => new THREE.MeshStandardMaterial({ 
    color: '#e4e8ec', 
    roughness: 0.3, 
    metalness: 0.1 
  }), []);

  // Global seamless loop motion
  const spinY = u * Math.PI * 2; // 360 degree horizontal rotation
  const tiltX = Math.sin(u * Math.PI * 2) * 0.2; // Gentle breathing tilt
  const tiltZ = Math.cos(u * Math.PI * 2) * 0.1;

  return (
    <group rotation={[tiltX, spinY, tiltZ]}>
      {mainAtoms.map((atom, i) => (
        <mesh key={`m_${i}`} position={atom.pos} geometry={sphereGeoMain}>
          <meshPhysicalMaterial 
            color={atom.color} 
            roughness={0.15} 
            clearcoat={1.0} 
            clearcoatRoughness={0.05} 
            metalness={0.05} 
          />
        </mesh>
      ))}
      {sideAtoms.map((atom, i) => (
        <mesh key={`s_${i}`} position={atom.pos} geometry={sphereGeoSide}>
           <meshPhysicalMaterial 
            color={atom.color} 
            roughness={0.2} 
            clearcoat={0.8} 
            clearcoatRoughness={0.1}
          />
        </mesh>
      ))}
      {edges.map((edge, i) => {
        const distance = edge.p1.distanceTo(edge.p2);
        const pos = edge.p1.clone().lerp(edge.p2, 0.5);
        const quat = new THREE.Quaternion().setFromUnitVectors(
          new THREE.Vector3(0, 1, 0),
          edge.p2.clone().sub(edge.p1).normalize()
        );
        return (
          <mesh 
            key={`e_${i}`} 
            position={pos} 
            quaternion={quat} 
            geometry={cylinderGeo} 
            material={bondMat} 
            scale={[1, distance, 1]} 
          />
        );
      })}
    </group>
  );
};

export const MolecularNetwork: React.FC<MolecularNetworkProps> = ({
  width = 3840,
  height = 2160,
  totalFrames = 240,
  speed = 1,
}) => {
  const frame = useCurrentFrame();
  const u = (frame / totalFrames) * Math.max(1, Math.round(speed));

  return (
    <div style={{ width, height, backgroundColor: '#000000' }}>
      <ThreeCanvas
        width={width}
        height={height}
        camera={{ position: [0, 0, 18], fov: 40, near: 0.1, far: 100 }}
        gl={{ antialias: true, alpha: false }}
        style={{ background: '#000000' }}
      >
        <Environment />
        {/* Crisp lighting setup for glossy reflections */}
        <ambientLight intensity={0.2} />
        <directionalLight position={[10, 20, 15]} intensity={2.5} />
        <directionalLight position={[-10, -10, -15]} intensity={1.0} />
        <pointLight position={[0, 0, 10]} intensity={1.5} />
        <Molecule u={u} />
      </ThreeCanvas>
    </div>
  );
};
